### ISSUE TITLE
找不到 ID 为xxxxx 的数据库。确保与您的集成共享相关页面和数据库。

### ISSUE THREAD

**Issue by lingPoint** [2nthony/blogkit#50]
<html>
<body>

克隆 github.com/lingPoint/blog2（分支：主，提交：2456763）
--
23:21:21.197 | 以前的构建缓存不可用
23:21:21.254 | 克隆完成：302.514ms
23:21:21.324 | 运行“vercel build”
23:21:21.721 | 韦塞尔 CLI 28.14.1
23:21:21.923 | 正在安装依赖项...
23:21:22.183 | 纱线安装 v1.22.17
23:21:22.207 | 信息 未找到锁定文件。
23:21:22.212 | [1/4] 正在解析包...
23:21:24.991 | [2/4] 正在获取包...
23:21:29.729 | [3/4] 链接依赖关系...
23:21:31.007 | [4/4] 构建新鲜包装...
23:21:31.012 | 成功 保存了锁定文件。
23:21:31.015 | 在 8.84 秒内完成。
23:21:31.033 | 检测到 下.js版本：12.1.0
23:21:31.034 | 运行“纱线运行构建”
23:21:31.176 | 纱线运行 v1.22.17
23:21:31.202 | $ 下一个构建
23:21:31.909 | 警告 - 检测到 next.config.js，未找到导出的配置。https://nextjs.org/docs/messages/empty-configuration
23:21:32.018 | 注意：接下来.js现在收集有关使用情况的完全匿名遥测数据。
23:21:32.018 | 此信息用于制定 Next.js 的路线图并确定功能的优先级。
23:21:32.018 | 您可以通过访问以下 URL 了解更多信息，包括如果您不想参与此匿名计划，如何选择退出：
23:21:32.018 | https://nextjs.org/telemetry
23:21:32.018 |  
23:21:32.254 | 信息 - 检查类型的有效性...
23:21:33.756 | 警告 - 未检测到 ESLint 配置。运行下一个 lint 开始设置
23:21:33.760 | 信息 - 创建优化的生产版本...
23:21:40.365 | 信息 - 编译成功
23:21:40.365 | 信息 - 正在收集页面数据...
23:21:41.039 | @notionhq/客户端警告：请求失败 {
23:21:41.039 | 代码：“object_not_found”，
23:21:41.040 | 消息：“找不到 ID 为 0fbea1e8-28e7-422d-bd7c-59e9308a33da。确保与您的集成共享相关页面和数据库。
23:21:41.040 | }
23:21:41.040 |  
23:21:41.041 | > 发生生成错误
23:21:41.042 | 错误 [APIResponseError]： 找不到 ID 为 0fbea1e8-28e7-422d-bd7c-59e9308a33da 的数据库。确保与您的集成共享相关页面和数据库。
23:21:41.043 | at buildRequestError （/vercel/path0/node_modules/@notionhq/client/build/src/errors.js：162：16）
23:21:41.043 | at Client.request （/vercel/path0/node_modules/@notionhq/client/build/src/Client.js：304：54）
23:21:41.043 | at process.processTicksAndRejections （node：internal/process/task_queues：95：5） {
23:21:41.043 | type： 'APIResponseError'，
23:21:41.043 | 代码：“object_not_found”，
23:21:41.043 | 状态： 404，
23:21:41.043 | 标头：{}，
23:21:41.043 | body：“{”object“：”error“，”status“：404，”code“：”object_not_found“，”message“：”找不到 ID 为 0fbea1e8-28e7-422d-bd7c-59e9308a33da。确保与您的集成共享相关页面和数据库。
23:21:41.043 | }
23:21:41.075 | 错误命令失败，退出代码为 1。
23:21:41.075 | info 有关此命令的文档，请访问 https://yarnpkg.com/en/docs/cli/run。
23:21:41.090 | 错误：命令“yarn run build”退出，但 1

</body>
</html>

**Comment by lingPoint** [comment]
用的 这个库https://github.com/2nthony/blog

**Comment by 2nthony** [comment]
不知道你有没有设置 connections， 应该是参考 https://github.com/2nthony/blogkit-notion-starter#get-environment-variables 来获得 token

![image](https://user-images.githubusercontent.com/19513289/216370424-f119d24f-6609-4b1d-a4c1-935a0bde6d5e.png)

**Comment by lingPoint** [comment]
谢谢！问题解决了
